---
title: "10X Diffusion pseudotime analysis"
author: "James Kinchen, University of Oxford"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
    html_document:
        toc: true
        toc_float: true
        highlight: tango
        number_sections: true
        code_folding: hide
        dev: [png,pdf]
params:
  script_name:
    input: text
    label: 'Script identifier'
    value: 'DPT'
---

```{r setup, include=FALSE, cache=FALSE}

knitr::opts_chunk$set(echo = TRUE, fig.width = 8, fig.height = 6, message = FALSE, warning = FALSE, cache = TRUE, 
                      cache.path = paste0("cache/",params$script_name,"/"),
                      fig.path = paste0("output/",params$script_name,"/"))

```

```{r setup_2, include=FALSE, cache=FALSE}

options(stringsAsFactors = FALSE)
library(Seurat)
#library(dplyr)
library(destiny)
library(scater)
library(colorspace)

```

# Extract expression data for fibroblast like cells in the healthy dataset

Use precomputed for reproducibility

```{r get_exprs, eval=FALSE}

#Load data
ds <- readRDS("output/cluster_biology.RData")

# Subset to fibroblasts
sc <- ds$sc_hc
sc <- SetIdent(sc, ident.use = sc@data.info$clust_names)

sc <- SubsetData(sc, ident.use = c("Str3","Str1.2","Str1.1","Str1.3","Str2"))

# Recalculate variable genes
sc <- MeanVarPlot(sc ,fxn.x = expMean, fxn.y = logVarDivMean, x.low.cutoff = 0.0125, x.high.cutoff = 4, y.cutoff = 0.5, do.contour = F)
print(paste(length(sc@var.genes), "variable genes"))

# Extract normalised expression values to an SCESet
featureAnno <- data.frame(gene_symbol=sc@var.genes)

rownames(featureAnno) <- featureAnno$gene_symbol

sce <- newSCESet(
  exprsData = as.matrix(sc@data[sc@var.genes,]),
  phenoData = AnnotatedDataFrame(sc@data.info),
  featureData = AnnotatedDataFrame(featureAnno),
  logExprsOffset = 1,
  lowerDetectionLimit = 0
)

```

# Generate diffusion map

Use a precomputed version for reproducibility

```{r diff_map, eval=FALSE}

dm <- DiffusionMap(sce, k=500, rotate = TRUE)

saveRDS(list(sce = sce, dm = dm), file = "output/DPT/diffmap.RData")

```

```{r plot_clusts}

pre_comp <- readRDS("output/DPT/diffmap.RData")
sce <- pre_comp$sce
dm <- pre_comp$dm

p3d <- plot(dm, c(1,3,2), col = rainbow_hcl(5)[as.factor(pData(sce)$clust_names)], pch = 20, box = FALSE, cex.symbols = 0.5)
legend(p3d$xyz.convert(0.1, 0, 1), col= rainbow_hcl(5), bg="white", 
       lty=c(1,1), lwd=8, xjust = 0, yjust=1, legend = levels(as.factor(pData(sce)$clust_names)), cex = 1.1)

```

## DC eigenvalues

```{r diff_eigen, fig.width=6, fig.height=5}

plot(eigenvalues(dm), ylim = 0:1, pch = 20,
              xlab = 'Diffusion component (DC)', ylab = 'Eigenvalue')

```

# Calculate pseudotime

```{r dpt, fig.width=6, fig.height=5}

dpt <- DPT(dm)
plot(dpt,c(1,3,2), root = 1, paths_to = c(2,3), pch = 20, 
     cex.symbols = 0.5, w_width = 0.3, legend_main="", main = "Diffusion Pseudotime", col_path = c("blue","red"))

```

## Pseudotime specific gene expression

```{r dpt_genes, fig.width=6, fig.height=5}

plot(dpt,c(1,3,2), root = 1, paths_to = c(2,3), pch = 20, col_by="Ebf1",
     cex.symbols = 0.5, w_width = 0.3, legend_main = "", main = "Early - Ebf1", col_path = c("blue","red"))
plot(dpt,c(1,3,2), root = 1, paths_to = c(2,3), pch = 20, col_by="Thy1",
     cex.symbols = 0.5, w_width = 0.3, legend_main = "", main = "Mid - Thy1", col_path = c("blue","red"))
plot(dpt,c(1,3,2), root = 1, paths_to = c(2,3), pch = 20, col_by="Adamdec1",
     cex.symbols = 0.5, w_width = 0.3, legend_main = "", main = "Late - Adamdec1", col_path = c("blue","red"))

```

## Branch specific gene expression

```{r branch_genes, fig.width=6, fig.height=5}

plot(dpt,c(1,3,2), root = 1, paths_to = c(2,3), pch = 20, col_by="Il33",
     cex.symbols = 0.5, w_width = 0.3, legend_main = "", main = "Branch 1 - Il33", col_path = c("blue","red"))
plot(dpt,c(1,3,2), root = 1, paths_to = c(2,3), pch = 20, col_by="Ptgs2",
     cex.symbols = 0.5, w_width = 0.3, legend_main = "", main = "Branch 2 - Ptgs2", col_path = c("blue","red"))

```

